services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        HOSTNAME: ${HOSTNAME:-spark}
        CENTRAL_PROMETHEUS_URL: ${CENTRAL_PROMETHEUS_URL}
        BASIC_AUTH_USER: ${BASIC_AUTH_USER:-}
        BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-}
    container_name: monitoring-prometheus
    restart: unless-stopped
    user: "nobody"
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=agent'
      - '--storage.agent.path=/prometheus'
      - '--web.listen-address=0.0.0.0:9090'
      - '--web.enable-lifecycle'
    depends_on:
      - cadvisor

  cadvisor:
    image: ghcr.io/google/cadvisor:latest
    container_name: monitoring-cadvisor
    restart: unless-stopped
    privileged: true
    networks:
      - monitoring
    expose:
      - 8080
    command:
      - '-housekeeping_interval=15s'
      - '-docker_only=true'
      - '-store_container_labels=false'
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave

networks:
  monitoring:
    driver: bridge
